---
title: Simpris
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Simpris
description: Simpris Project Management System
author: Simpris
author_email: simpricity@gmail.com
category_dir: "/"
baseurl: 
url: https://www.simpris.com
permalink: pretty
paginate: 3
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
image: https://res.cloudinary.com/goodlycode/image/upload/v1585171877/simpris/Simpris02-big.png
