---
title: Simpris
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
name: Simpris
description: Simpris Project Management System
author: Simpris
author_email: simpricity@gmail.com
category_dir: "/"
baseurl: https://grafrajohn.github.io/si
url: https://grafrajohn.github.io/si
permalink: pretty
paginate: 3
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
image: https://res.cloudinary.com/hands.jpg
