---
title: Si
timezone: UTC
collections:
  oils:
    title: Oils
    output: false
  posts:
    title: Posts
    output: true
  prints:
    title: Prints
    output: false
  uploads:
    title: Uploads
    output: true
  watercolours:
    title: Watercolours
    output: false
name: Beverlonian
description: Beverley Life
author: Beverlonian
author_email: beverlonian@gmail.com
category_dir: "/"
baseurl: https://grafrajohn.github.io/beverlonian
url: https://grafrajohn.github.io/beverlonian
permalink: pretty
paginate: 3
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
image: https://res.cloudinary.com/hands.jpg
